export const Types = [
    {id: 75, name: '3D'},
    {id: 11, name: 'Adult'},
    {id: 77, name: 'Animal girl'},
    {id: 99, name: 'Artist'},
    {id: 22, name: 'Bạo Dâm'},
    {id: 87, name: 'CG'},
    {id: 50, name: 'Chơi Hai Lỗ'},
    {id: 13, name: 'Complete'},
    {id: 96, name: 'Côn Trùng'},
    {id: 27, name: 'Cosplay'},
    {id: 45, name: 'Doujinshi'},
    {id: 67, name: 'Đồ Bơi'},
    {id: 21, name: 'Ecchi'},
    {id: 95, name: 'Elf'},
    {id: 20, name: 'Fantasy'},
    {id: 93, name: 'Furry'},
    {id: 63, name: 'Futanari'},
    {id: 41, name: 'Gangbang'},
    {id: 85, name: 'Gender Bender'},
    {id: 56, name: 'Giáo Viên'},
    {id: 4, name: 'Group'},
    {id: 46, name: 'Guro'},
    {id: 26, name: 'Hài Hước'},
    {id: 71, name: 'Hãm Hiếp'},
    {id: 23, name: 'Harem'},
    {id: 28, name: 'Hầu Gái'},
    {id: 51, name: 'Hậu Môn'},
    {id: 7, name: 'Housewife'},
    {id: 81, name: 'Kinh Dị'},
    {id: 98, name: 'Kogal'},
    {id: 15, name: 'Lãng Mạn'},
    {id: 70, name: 'Lão Gìa Dâm'},
    {id: 57, name: 'Loạn Luân'},
    {id: 31, name: 'Loli'},
    {id: 55, name: 'Mang Thai'},
    {id: 3, name: 'Manhwa'},
    {id: 18, name: 'Mắt Kính'},
    {id: 2, name: 'Mature'},
    {id: 101, name: 'Milf'},
    {id: 17, name: 'Mind Break'},
    {id: 94, name: 'Mind Control'},
    {id: 72, name: 'Monster Girl'},
    {id: 14, name: 'Ngực Lớn'},
    {id: 19, name: 'Ngực Nhỏ'},
    {id: 66, name: 'Nô Lệ'},
    {id: 10, name: 'NTR'},
    {id: 52, name: 'Nữ Sinh'},
    {id: 49, name: 'OneShot'},
    {id: 82, name: 'Quái Vật'},
    {id: 100, name: 'Scat'},
    {id: 12, name: 'Series'},
    {id: 34, name: 'Shota'},
    {id: 74, name: 'Supernatural'},
    {id: 68, name: 'Thể Thao'},
    {id: 80, name: 'Thú Vật'},
    {id: 88, name: 'Trap'},
    {id: 76, name: 'Truyện Comic'},
    {id: 61, name: 'Truyện Không Che'},
    {id: 16, name: 'Truyện Màu'},
    {id: 69, name: 'Truyện Ngắn'},
    {id: 48, name: 'Virgin'},
    {id: 84, name: 'Xúc Tua'},
    {id: 73, name: 'Y Tá'},
    {id: 86, name: 'Yaoi'},
    {id: 65, name: 'Yuri'},
]

